services:
  - type: web
    name: cvtc-wallet-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    ports:
      - 4000
    rootDir: backend
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: OPERATOR_PRIVATE_KEY
        sync: false
      - key: CVTC_ONBOARDING_CONTRACT_ADDRESS
        sync: false
      - key: BNB_RPC_URL
        sync: false
      - key: PRIVY_APP_ID
        sync: false
      - key: PRIVY_APP_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: PORT
        value: 4000

  - type: static_site
    name: cvtc-wallet-frontend
    buildCommand: npm run build
    publishPath: dist
    rootDir: frontend
